apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-api-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: easy-api-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "{{ .Values.containerPort }}"
      labels:
        app: easy-api-service
    spec:
      containers:
        - name: web-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}