apiVersion: v1
kind: Service
metadata:
  name: easy-api-service
  labels:
    app: easy-api-service
spec:
  selector:
    app: easy-api-service
  ports:
    - port: 8080
      targetPort: {{ .Values.containerPort }}
