apiVersion: v1
kind: Service
metadata:
  name: easy-spa-service
  labels:
    app: easy-spa-service
spec:
  selector:
    app: easy-spa-service
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
