apiService:
  host: easy-api-service.default.svc.cluster.local
  port: 8080

spaService:
  host: easy-spa-service.default.svc.cluster.local
  port: 80


image:
  repository: envoyproxy/envoy
  tag: v1.26-latest

replicaCount: 1

