apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-spa-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: easy-spa-service
  template:
    metadata:
      labels:
        app: easy-spa-service
    spec:
      containers:
        - name: web-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}