apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    http_port = 80
    root_url = https://localhost:8443/grafana/
    serve_from_sub_path = true
    [auth]
    cookie_secure = true
    cookie_samesite = none
    [live]
    allowed_origins = https://localhost:8443