vault:
  server:
    extraArgs:
      - "-dev"
      - "-dev-root-token-id="
    standalone:
      enabled: true
    dataStorage:
      enabled: false
    ha:
      enabled: false
    ingress:
      enabled: false
    service:
      type: ClusterIP
      port: 8200