apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: NodePort
  selector:
    app: envoy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32114  # Example NodePort
      protocol: TCP